env:
  - namespace: "a" # specify which namespace use this env, if it is not set,env scope is global
    env: # valuse must be string type
      URL: https://baidu.com
      shortTimeOut: 3s
      longTimeOut: 10s
request:
  timeout: 5s
respose:
  showUrl: true # show request url
  showHeader: true # show response header
  showCode: true #  show response code
  showBody: false # show response body
  showTimeConsumption: true # show request time consumption
