env:
  - namespace: "a" # specify which namespace use this env, if it is not set,env scope is global
    env: # valuse must be string type
      URL: https://baidu.com
      shortTimeOut: 3s
      longTimeOut: 10s
